apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: presidential-dove-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: presidential-dove-python 
  name: presidential-dove-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: presidential-dove-python 
